from tkinter import *
def calc():
    n1=float(e2.get())
    n2=float(e3.get())
    n3=n2/100
    r=n1/(n3**2)
    res.set(r)
    if r<18.5:
        calc.set("under weight")
    elif r<24.9:
        calc.set("normal weight")
    elif r<29.9:
        calc.set("over weight")
    else:
        calc.set("obesity")
app=Tk()
app.title("BMI CALULATOR")
l1=Label(app,text="age")
e1=Entry(app)
l2=Label(app,text="enter your weight in kg")
e2=Entry(app)
l3=Label(app,text="enter your height in cm")
e3=Entry(app)
btn=Button(app,text="calculate",command=calc)
res=StringVar()
res.set("")
calc=StringVar()
calc.set("")
l4=Label(app,text="result")
e4=Entry(app,textvariable=res)
l5=Label(app,text="BMI categories")
e5=Entry(app,textvariable=calc)
l1.grid(row=0,column=0)
e1.grid(row=0,column=1)
l2.grid(row=1,column=0)
e2.grid(row=1,column=1)
l3.grid(row=2,column=0)
e3.grid(row=2,column=1)
btn.grid(row=3,column=0)
l4.grid(row=4,column=0)
e4.grid(row=4,column=1)
l5.grid(row=5,column=0)
e5.grid(row=5,column=1)
app.mainloop()