from tkinter import *
root=Tk()
mymenu=Menu(root)
root.config(menu=mymenu)
submenu=Menu(mymenu)
mymenu.add_cascade(label="File",menu=submenu)
submenu.add_command(label="new file")
submenu.add_command(label="open file")
submenu.add_separator()
submenu.add_command(label="open folder")
submenu.add_command(label="new window")
newmenu=Menu(mymenu)
mymenu.add_cascade(label="edit",menu=newmenu)
newmenu.add_command(label="undo")
newmenu.add_command(label="redo")
newmenu.add_separator()
newmenu.add_command(label="cut")
newmenu.add_command(label="copy")
newmenu.add_command(label="paste")
view=Menu(mymenu)
mymenu.add_cascade(label="view",menu=view)
view.add_command(label="open window")
view.add_separator()
view.add_command(label="search")
view.add_command(label="run")
view.add_command(label="testing")
root.mainloop()



"""toolbar and statusbar"""
# from tkinter import *
# root=Tk()
# toolbar=Frame(root,bg='red')
# btn=Button(toolbar,text='crop')
# btn1=Button(toolbar,text='done')
# btn.pack(side=LEFT,padx=2,pady=2)
# btn1.pack(side=RIGHT,padx=2,pady=2)
# toolbar.pack(fill='x',side=TOP)
# statusbar=Label(root,text="this is statusbar",anchor=W,bg='yellow',fg='black')
# statusbar.pack(fill='x',side=BOTTOM)
# root.mainloop()