# Generated by Django 5.0.1 on 2024-01-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='category',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='language',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='screen',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default='address', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default='anu@gmail.com', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(default='1234567896'),
            preserve_default=False,
        ),
    ]
